import type { Locale } from "@/lib/i18n";

export type DayKey = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type ShiftWindow = { start: string; end: string };

export type MockCaregiver = {
  id: string;
  firstName: string;
  lastInitial: string;
  miles: number;
  languages: Array<"English" | "Spanish" | "Creole">;
  drives: boolean;
  role: "HHA" | "CNA";
  years: number;
  certifications: string[];
  /** Omitted when the demo profile does not display a gender. */
  gender?: "female" | "male";
  rateMin: number;
  rateMax: number;
  bio: string;
  bioEs: string;
  window: string;
  windowEs: string;
  area: string;
  areaEs: string;
  lat: number;
  lng: number;
  /** 24-hour HH:MM windows. A real schedule API can replace this shape. */
  availability: Partial<Record<DayKey, ShiftWindow>>;
};

export const MOCK_CAREGIVERS: MockCaregiver[] = [
  {
    id: "c1",
    firstName: "Xiomara",
    lastInitial: "R",
    miles: 1.2,
    languages: ["Spanish", "English"],
    drives: true,
    role: "HHA",
    years: 6,
    certifications: ["HHA", "CPR"],
    gender: "female",
    rateMin: 18,
    rateMax: 22,
    bio: "Weekday mornings. Comfortable with transfers and meal prep.",
    bioEs: "Mañanas entre semana. Cómoda con traslados y preparación de comidas.",
    availability: {
      mon: { start: "08:00", end: "14:00" },
      tue: { start: "08:00", end: "14:00" },
      wed: { start: "08:00", end: "14:00" },
      thu: { start: "08:00", end: "14:00" },
      fri: { start: "08:00", end: "14:00" },
    },
    window: "Tue 8:00 AM – 2:00 PM",
    windowEs: "Mar 8:00 a. m. – 2:00 p. m.",
    area: "Brickell",
    areaEs: "Brickell",
    lat: 25.761,
    lng: -80.193,
  },
  {
    id: "c2",
    firstName: "Niurka",
    lastInitial: "D",
    miles: 2.1,
    languages: ["Spanish"],
    drives: false,
    role: "HHA",
    years: 4,
    certifications: ["HHA"],
    gender: "female",
    rateMin: 16,
    rateMax: 20,
    bio: "Prefers shorter visits nearby. Does not drive.",
    bioEs: "Prefiere visitas cortas cerca. No conduce.",
    availability: {
      tue: { start: "07:00", end: "15:00" },
      wed: { start: "07:00", end: "15:00" },
      thu: { start: "07:00", end: "15:00" },
    },
    window: "Tue 7:00 AM – 3:00 PM",
    windowEs: "Mar 7:00 a. m. – 3:00 p. m.",
    area: "Little Havana",
    areaEs: "La Pequeña Habana",
    lat: 25.7654,
    lng: -80.2195,
  },
  {
    id: "c3",
    firstName: "Jennifer",
    lastInitial: "L",
    miles: 3.4,
    languages: ["English", "Spanish"],
    drives: true,
    role: "CNA",
    years: 8,
    certifications: ["CNA", "BLS"],
    gender: "female",
    rateMin: 22,
    rateMax: 28,
    bio: "Evenings only. Used to medication reminders.",
    bioEs: "Solo tardes. Acostumbrada a recordatorios de medicación.",
    availability: { tue: { start: "17:00", end: "21:00" } },
    window: "Tue 5:00 PM – 9:00 PM",
    windowEs: "Mar 5:00 p. m. – 9:00 p. m.",
    area: "Wynwood",
    areaEs: "Wynwood",
    lat: 25.8042,
    lng: -80.1994,
  },
  {
    id: "c4",
    firstName: "Marbelin",
    lastInitial: "A",
    miles: 6.2,
    languages: ["Spanish"],
    drives: false,
    role: "HHA",
    years: 3,
    certifications: ["HHA"],
    gender: "female",
    rateMin: 17,
    rateMax: 21,
    bio: "One midweek morning. Light housekeeping and companionship.",
    bioEs: "Una mañana entre semana. Tareas ligeras del hogar y compañía.",
    availability: { wed: { start: "08:00", end: "14:00" } },
    window: "Wed 8:00 AM – 2:00 PM",
    windowEs: "Mié 8:00 a. m. – 2:00 p. m.",
    area: "Coral Gables",
    areaEs: "Coral Gables",
    lat: 25.7215,
    lng: -80.2684,
  },
  {
    id: "c5",
    firstName: "Ana",
    lastInitial: "P",
    miles: 8.4,
    languages: ["Spanish", "English", "Creole"],
    drives: true,
    role: "CNA",
    years: 11,
    certifications: ["CNA", "CPR"],
    gender: "female",
    rateMin: 24,
    rateMax: 30,
    bio: "Thursday mornings. Speaks English, Spanish, and Creole.",
    bioEs: "Jueves por la mañana. Habla inglés, español y criollo.",
    availability: { thu: { start: "09:00", end: "13:00" } },
    window: "Thu 9:00 AM – 1:00 PM",
    windowEs: "Jue 9:00 a. m. – 1:00 p. m.",
    area: "Kendall",
    areaEs: "Kendall",
    lat: 25.6793,
    lng: -80.3173,
  },
  {
    id: "c6",
    firstName: "Luis",
    lastInitial: "M",
    miles: 7.1,
    languages: ["Spanish"],
    drives: true,
    role: "HHA",
    years: 5,
    certifications: ["HHA"],
    gender: "male",
    rateMin: 18,
    rateMax: 23,
    bio: "Early Monday start. Drives to the visit.",
    bioEs: "Empieza temprano el lunes. Conduce hasta la visita.",
    availability: { mon: { start: "06:00", end: "14:00" } },
    window: "Mon 6:00 AM – 2:00 PM",
    windowEs: "Lun 6:00 a. m. – 2:00 p. m.",
    area: "Hialeah",
    areaEs: "Hialeah",
    lat: 25.8576,
    lng: -80.2781,
  },
  {
    id: "c7",
    firstName: "Carmen",
    lastInitial: "S",
    miles: 9.0,
    languages: ["Spanish", "English"],
    drives: false,
    role: "HHA",
    years: 9,
    certifications: ["HHA", "CPR"],
    gender: "female",
    rateMin: 19,
    rateMax: 24,
    bio: "Fridays. Companion care and errands on foot.",
    bioEs: "Viernes. Compañía y recados a pie.",
    availability: { fri: { start: "08:00", end: "16:00" } },
    window: "Fri 8:00 AM – 4:00 PM",
    windowEs: "Vie 8:00 a. m. – 4:00 p. m.",
    area: "North Miami",
    areaEs: "North Miami",
    lat: 25.8901,
    lng: -80.1867,
  },
  {
    id: "c8",
    firstName: "Rosa",
    lastInitial: "T",
    miles: 5.5,
    languages: ["English"],
    drives: true,
    role: "CNA",
    years: 7,
    certifications: ["CNA", "BLS"],
    rateMin: 23,
    rateMax: 29,
    bio: "Wednesday afternoons into the evening.",
    bioEs: "Miércoles por la tarde hasta la noche.",
    availability: { wed: { start: "12:00", end: "20:00" } },
    window: "Wed 12:00 PM – 8:00 PM",
    windowEs: "Mié 12:00 p. m. – 8:00 p. m.",
    area: "Coconut Grove",
    areaEs: "Coconut Grove",
    lat: 25.727,
    lng: -80.242,
  },
  {
    id: "c9",
    firstName: "Elena",
    lastInitial: "V",
    miles: 4.8,
    languages: ["Spanish", "English", "Creole"],
    drives: true,
    role: "HHA",
    years: 12,
    certifications: ["HHA", "CPR"],
    gender: "female",
    rateMin: 20,
    rateMax: 26,
    bio: "Saturdays. English, Spanish, and Creole.",
    bioEs: "Sábados. Inglés, español y criollo.",
    availability: { sat: { start: "09:00", end: "15:00" } },
    window: "Sat 9:00 AM – 3:00 PM",
    windowEs: "Sáb 9:00 a. m. – 3:00 p. m.",
    area: "Miami Beach",
    areaEs: "Miami Beach",
    lat: 25.7907,
    lng: -80.13,
  },
  {
    id: "c10",
    firstName: "Pedro",
    lastInitial: "G",
    miles: 10.2,
    languages: ["Spanish"],
    drives: false,
    role: "CNA",
    years: 2,
    certifications: ["CNA"],
    gender: "male",
    rateMin: 21,
    rateMax: 27,
    bio: "Thursday daytime. Newer to the work, rides the bus.",
    bioEs: "Jueves de día. Recién en el oficio, se mueve en bus.",
    availability: { thu: { start: "07:00", end: "15:00" } },
    window: "Thu 7:00 AM – 3:00 PM",
    windowEs: "Jue 7:00 a. m. – 3:00 p. m.",
    area: "Doral",
    areaEs: "Doral",
    lat: 25.8195,
    lng: -80.3553,
  },
];

export function caregiverWindow(c: MockCaregiver, locale: Locale) {
  return locale === "es" ? c.windowEs : c.window;
}

export function caregiverArea(c: MockCaregiver, locale: Locale) {
  return locale === "es" ? c.areaEs : c.area;
}
